<!-- ========================= Section 1 controlpeso======================= -->
	<div class="section" id="controlpeso" data-anchor="controlPeso">
	
	<!-- ========================= controlpeso Slide 1 [Portada principal]======================= -->
	<div class="slide" id="controlpeso_slide1"><!-- contenido--></div><!-- end Slide 1 familia 1 -->

	<!-- ========================= controlpeso Slide 2 ======================= -->
	<div class="slide" id="controlpeso_slide2">
		<div class="container-fluid">
			<img src="<?php echo asset('images/portadas/pagina2_2.png')?>" class="img-fluid" usemap="#image-map">
			<!-- Image Map Generated by http://www.image-map.net/ -->
			<map name="image-map">
			    <area  name="pagina2_2png" coords="1004,1399,500,601" shape="rect" onclick="verInfo('514');">
			</map>
			</div><!-- end container fluid -->
			</div><!-- end Slide 2 familia 1 -->

		<!-- ========================= controlpeso Slide 3 ======================= -->
	<div class="slide" id="controlpeso_slide3">
		<!--<div class="contenido">-->

			<!----------------------------------Producto 1------------------------------------------------------------>
			<div class="row simpleCart_shelfItem"><!-- row producto 1 -->
				 <div class="product-grid2 ">
				 <img src="<?php echo asset('images/productos/controlpeso/tecnocarb.jpg')?>" class="rounded mx-auto d-block img-fluid img-producto-arriba">
				 <!-- FRANJA PRIMER PRODUCTO VA DEBAJO DE IMAGEN -->
				 <div class="franja-producto">
						<div class="row div-titulo-producto"><!-- row titulo-producto -->

							<div class="col col-sm-2"></div><!-- cuadre de separacion izquierda -->

				 			<div class="col-sm"><!-- col para titulo producto -->
				 			<span class="titulo-productos item_name">T-NOCARB</span><br>
				 			<span class="subtitulo-productos">DOYPACK 14 X 5 gr / CV:25</span>
				 			</div><!-- end col titulo producto -->

				 			<div class="col-sm"><!-- col precio -->
				 			<span class="symbol-precio">S/.</span> <span class="precio">50</span> <span class="precio-decimal">.60</span></span><span style="display: none;" class="item_price">50.60</span>
				 			</div><!-- end col precio -->

				 		</div><!-- end row titulo producto-->
				 </div><!-- end franja producto -->

				 <!-- botones -->
				<ul class="social">
                        <li><a onclick="verInfo('tnocarb');" data-tip="Ver Descripción"><i class="fa fa-eye"></i></a></li>
                        <li><a href="javascript:;"  class="item_add" data-tip="Añadir al carrito"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
			
			</div><!-- end col producto 1 -->
			</div><!-- end row producto 1 -->
			<!----------------------------------Producto 1------------------------------------------------------------>

			<!-- division -->
			<div class="divison-productos"></div>
			<!-- division -->

			<!----------------------------------Producto 2------------------------------------------------------------>
			<div class="row simpleCart_shelfItem"><!-- row producto 2 -->
				<!-- FRANJA SEGUNDO PRODUCTO VA ENCIMA DE IMAGEN -->
				<div class="franja-producto">
						<div class="row div-titulo-producto"><!-- row titulo-producto -->

							<div class="col col-sm-2"></div><!-- cuadre de separacion izquierda -->

				 			<div class="col-sm"><!-- col para titulo producto -->
				 			<span class="titulo-productos item_name">THERMO T3</span><br>
				 			<span class="subtitulo-productos">DOYPACK 14 X 5 gr / CV:25</span>
				 			</div><!-- end col titulo producto -->

				 			<div class="col-sm"><!-- col precio -->
				 			<span class="symbol-precio">S/.</span> <span class="precio">50</span> <span class="precio-decimal">.60</span></span><span style="display: none;" class="item_price">50.60</span>
				 			</div><!-- end col precio -->

				 		</div><!-- end row producto 2-->
				 </div><!-- end franja producto -->

				 <div class="col-sm product-grid2">
				 <img src="<?php echo asset('images/productos/controlpeso/controlpeso_termot3.jpg') ?>" class="rounded mx-auto d-block img-fluid mt-5 img-producto-abajo">
				<ul class="social">
                        <li><a onclick="verInfo('exampleModal');" data-tip="Ver Descripción"><i class="fa fa-eye"></i></a></li>
                        <li><a href="javascript:;"  class="item_add" data-tip="Añadir al carrito"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
			
			</div><!-- end col producto 2 -->
			</div><!-- end row producto 2 -->	

<!----------------------------------Producto 1------------------------------------------------------------>	

			<!--</div> contenido -->

		</div><!-- end Slide 3 familia 1 -->
</div><!-- end section familia 1 --->